"""Generate INDEX.md, registry.tsv and edges.tsv from frontmatter. Never
hand-edit those.

INDEX.md covers library/ only, so write-documentation PRs (inbox-only) never
touch generated files. Inbox depth: count files under inbox/.

edges.tsv is the flat-file relations table: one row per predicated relation
plus one row (predicate `related`) per plain related-link, library tier only.
recall.py walks it; publish_delta.py mirrors it into kg_edges.
"""

from pathlib import Path

from kglib import load_docs, load_schema, split_relation

ROOT = Path(__file__).resolve().parent


def render() -> tuple:
    """Returns (index_text, registry_text, edges_text) — used by validate.py
    drift check."""
    lib = load_docs(ROOT, tiers=("library",))
    _, preds = load_schema(ROOT)
    lines = [
        "# Library Index",
        "",
        "Generated by build_index.py — do not hand-edit. Library tier only.",
        "",
    ]
    for domain in sorted({d["domain"] for d in lib}):
        lines.append(f"## {domain}")
        for d in (x for x in lib if x["domain"] == domain):
            al = f" — aliases: {', '.join(d['aliases'])}" if d["aliases"] else ""
            lines.append(
                f"- [{d['file']}]({d['file']}) — {d['entity']} ({d['type']}){al}"
            )
        lines.append("")
    index_text = "\n".join(lines)
    registry_text = "".join(
        f"{d['entity']}\t{d['type']}\t{d['file']}\t{'|'.join(d['aliases'])}\n"
        for d in lib
    )
    edge_rows = []
    for d in lib:
        for rel in d["relations"]:
            s, p, o = split_relation(rel, preds)
            if p:
                edge_rows.append((s, p, o, d["file"]))
        for r in d["related"]:
            edge_rows.append((d["entity"], "related", r, d["file"]))
    edges_text = "".join(f"{s}\t{p}\t{o}\t{f}\n" for s, p, o, f in edge_rows)
    return index_text, registry_text, edges_text


def main() -> None:
    index_text, registry_text, edges_text = render()
    (ROOT / "INDEX.md").write_text(index_text, encoding="utf-8")
    (ROOT / "registry.tsv").write_text(registry_text, encoding="utf-8")
    (ROOT / "edges.tsv").write_text(edges_text, encoding="utf-8")
    inbox = load_docs(ROOT, tiers=("inbox",))
    lib = load_docs(ROOT, tiers=("library",))
    print(
        f"indexed {len(lib)} library files -> INDEX.md, registry.tsv, "
        f"edges.tsv ({len(inbox)} captures waiting in inbox/)"
    )


if __name__ == "__main__":
    main()
