"""Gold-question test runner. Stdlib only.

Each test is a gold question (or a governance invariant) run against the real
CLI tools via subprocess — no mocks, the tools are the unit. Run:

    python tests/test_gold.py

Exit 1 on any failure.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable
RESULTS = []


def run(script, *args, stdin=None):
    return subprocess.run(
        [PY, str(ROOT / script), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        cwd=ROOT,
        input=stdin,
    )


def check(name, ok, detail=""):
    RESULTS.append((name, ok, detail))
    print(f"{'PASS' if ok else 'FAIL'}  {name}" + (f"  — {detail}" if not ok else ""))


# --- edges.tsv is a build_index artifact ---------------------------------

def test_edges_tsv():
    run("build_index.py")
    p = ROOT / "edges.tsv"
    if not p.exists():
        check("edges.tsv generated by build_index.py", False, "file missing")
        return
    rows = [r.split("\t") for r in p.read_text(encoding="utf-8").splitlines() if r]
    check("edges.tsv generated by build_index.py", True)
    check(
        "edges.tsv rows are subject/predicate/object/source_file",
        all(len(r) == 4 for r in rows),
        f"bad row widths: {[r for r in rows if len(r) != 4][:3]}",
    )
    check(
        "edges.tsv carries the approval edges",
        ["Supplier Payments", "approved_by", "Founder",
         "library/ops/supplier-payments.md"] in rows,
        "Supplier Payments approved_by Founder row not found",
    )


# --- recall answers from structure ---------------------------------------

def test_recall_refund_approval():
    r = run("recall.py", "who needs to sign off on an £800 refund?")
    ok = r.returncode == 0
    out = r.stdout
    check("recall: £800 refund finds the approval edges",
          ok and "approved_by" in out and "Ops Manager" in out,
          f"rc={r.returncode} out={out[:200]!r} err={r.stderr[:200]!r}")
    check("recall: £800 refund injects the banded description",
          "£500" in out and "48" in out,
          "description with £500 band / 48-hour window not in output")


def test_recall_incident_escalation():
    r = run("recall.py", "who handles a severity-1 incident?")
    out = r.stdout
    check("recall: sev-1 incident names Support Lead AND Founder",
          "Support Lead" in out and "Founder" in out,
          f"out={out[:200]!r}")


def test_recall_supplier_terms():
    r = run("recall.py", "how long until a supplier invoice is paid?")
    out = r.stdout
    check("recall: supplier terms reachable via walk (30-day terms)",
          "30" in out,
          f"out={out[:200]!r}")


def test_recall_stub_description():
    r = run("recall.py", "what is a refund?")
    out = r.stdout
    check("recall: stubs get an automatic pointer description",
          "stub" in out.lower() and "refund-approvals.md" in out,
          f"out={out[:200]!r}")


def test_recall_hook_mode():
    r = run("recall.py", "--hook",
            stdin=json.dumps({"prompt": "who approves a supplier payment?"}))
    check("recall --hook: emits context for a seeded prompt",
          r.returncode == 0 and "approved_by" in r.stdout,
          f"rc={r.returncode} out={r.stdout[:200]!r} err={r.stderr[:200]!r}")
    r = run("recall.py", "--hook",
            stdin=json.dumps({"prompt": "completely unrelated smalltalk"}))
    check("recall --hook: silent success on an unseeded prompt",
          r.returncode == 0 and r.stdout.strip() == "",
          f"rc={r.returncode} out={r.stdout[:200]!r}")


# --- search head-noun match ----------------------------------------------

def test_search_onboarding():
    r = run("search.py", "what is onboarding")
    check("search: 'what is onboarding' hits onboarding-process.md",
          r.returncode == 0 and "onboarding-process.md" in r.stdout,
          f"rc={r.returncode} out={r.stdout[:200]!r}")


# --- alias-aware inbox entity gate ---------------------------------------

def test_inbox_entity_alias_collision():
    inbox = ROOT / "inbox" / "test-alias-operations-manager.md"
    inbox.write_text(
        "---\n"
        "title: Operations Manager capture\n"
        "entity: Operations Manager\n"
        "type: ROLE\n"
        "source:\n"
        "  - https://example.com/alias-gate\n"
        "updated: 2026-08-25\n"
        "---\n\nbody\n",
        encoding="utf-8",
    )
    try:
        r = run("validate.py")
        check("validate: inbox entity matching a library ALIAS is an error",
              r.returncode == 1 and "Operations Manager" in r.stdout
              and "alias" in r.stdout.lower(),
              f"rc={r.returncode} out={r.stdout[-400:]!r}")
    finally:
        inbox.unlink()


# --- temporal keys are legal vocabulary ----------------------------------

def test_temporal_keys():
    f = ROOT / "inbox" / "test-temporal.md"
    f.write_text(
        "---\n"
        "title: Temporal test\n"
        "entity: Temporal Test Entity\n"
        "type: PROCESS\n"
        "valid_from: 2026-03-01\n"
        "valid_to: 2026-03-31\n"
        "source:\n"
        "  - https://example.com/temporal\n"
        "updated: 2026-08-25\n"
        "---\n\nbody\n",
        encoding="utf-8",
    )
    try:
        r = run("validate.py", "--format", str(f))
        check("validate: valid_from/valid_to are known header keys",
              "unknown header key" not in r.stdout,
              f"out={r.stdout[:300]!r}")
        f.write_text(f.read_text(encoding="utf-8")
                     .replace("valid_to: 2026-03-31", "valid_to: not-a-date"),
                     encoding="utf-8")
        r = run("validate.py", "--format", str(f))
        check("validate: malformed valid_to is an error",
              r.returncode == 1 and "valid_to" in r.stdout,
              f"rc={r.returncode} out={r.stdout[:300]!r}")
    finally:
        f.unlink()


# --- baseline: the library itself stays clean ----------------------------

def test_validate_clean():
    r = run("validate.py")
    check("validate: full library passes with zero errors",
          r.returncode == 0,
          f"rc={r.returncode} out={r.stdout[-600:]!r}")


def main():
    test_edges_tsv()
    test_recall_refund_approval()
    test_recall_incident_escalation()
    test_recall_supplier_terms()
    test_recall_stub_description()
    test_recall_hook_mode()
    test_search_onboarding()
    test_inbox_entity_alias_collision()
    test_temporal_keys()
    test_validate_clean()
    failed = [n for n, ok, _ in RESULTS if not ok]
    print(f"\n{len(RESULTS) - len(failed)}/{len(RESULTS)} passed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
