"""Gold-question runner + governance invariants. Stdlib only.

Gold rows live in library/<domain>/GOLD.md as a markdown table
(| # | Question | Must contain | Source | Status |) — the table is the
single source; this runner parses it and executes every row against the
real CLI tools via subprocess. A row PASSES if "Must contain" appears in
recall.py output (case-insensitive) OR the Source file appears in
search.py results — the two retrieval paths; loud-fail only when both
miss. Adding a test = adding a row to the table.

The invariant tests below the gold runner are layer/governance checks
that don't belong to any domain table. Run:

    python tests/test_gold.py

Exit 1 on any failure.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable
RESULTS = []


def run(script, *args, stdin=None):
    return subprocess.run(
        [PY, str(ROOT / script), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        cwd=ROOT,
        input=stdin,
    )


def check(name, ok, detail=""):
    RESULTS.append((name, ok, detail))
    print(f"{'PASS' if ok else 'FAIL'}  {name}" + (f"  — {detail}" if not ok else ""))


# --- gold tables: parse library/*/GOLD.md and run every row ---------------

def parse_gold(path: Path) -> list:
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4 or cells[0] in ("#", "") or set(cells[0]) <= {"-"}:
            continue
        rows.append({"n": cells[0], "question": cells[1],
                     "must": cells[2], "source": cells[3]})
    return rows


def test_gold_tables():
    tables = sorted(ROOT.glob("library/*/GOLD.md"))
    if not tables:
        check("gold: at least one library/<domain>/GOLD.md exists", False,
              "no gold tables found")
        return
    for table in tables:
        domain = table.parent.name
        rows = parse_gold(table)
        check(f"gold[{domain}]: table parses (rows found)", bool(rows),
              f"{table} yielded no rows")
        for r in rows:
            rec = run("layers/graph-lite/recall.py", r["question"]).stdout
            sea = run("layers/graph-lite/search.py", r["question"]).stdout
            ok = r["must"].lower() in rec.lower() or r["source"] in sea
            check(f"gold[{domain}#{r['n']}]: {r['question']}", ok,
                  f"'{r['must']}' not in recall out ({rec[:120]!r}) and "
                  f"'{r['source']}' not in search out ({sea[:120]!r})")


# --- invariant: edges.tsv is a build_index artifact -----------------------

def test_edges_tsv():
    run("build_index.py")
    p = ROOT / "edges.tsv"
    if not p.exists():
        check("edges.tsv generated by build_index.py", False, "file missing")
        return
    rows = [r.split("\t") for r in p.read_text(encoding="utf-8").splitlines() if r]
    check("edges.tsv generated by build_index.py", True)
    check(
        "edges.tsv rows are subject/predicate/object/source_file",
        all(len(r) == 4 for r in rows),
        f"bad row widths: {[r for r in rows if len(r) != 4][:3]}",
    )


# --- invariant: stubs get an automatic pointer description ----------------

def test_recall_stub_description():
    r = run("layers/graph-lite/recall.py", "what is a refund?")
    out = r.stdout
    check("recall: stubs get an automatic pointer description",
          "stub" in out.lower() and "refund-approvals.md" in out,
          f"out={out[:200]!r}")


# --- invariant: hook mode emits when seeded, stays silent otherwise -------

def test_recall_hook_mode():
    r = run("layers/graph-lite/recall.py", "--hook",
            stdin=json.dumps({"prompt": "who approves a supplier payment?"}))
    check("recall --hook: emits context for a seeded prompt",
          r.returncode == 0 and "approved_by" in r.stdout,
          f"rc={r.returncode} out={r.stdout[:200]!r} err={r.stderr[:200]!r}")
    r = run("layers/graph-lite/recall.py", "--hook",
            stdin=json.dumps({"prompt": "completely unrelated smalltalk"}))
    check("recall --hook: silent success on an unseeded prompt",
          r.returncode == 0 and r.stdout.strip() == "",
          f"rc={r.returncode} out={r.stdout[:200]!r}")


# --- invariant: alias-aware inbox entity gate -----------------------------

def test_inbox_entity_alias_collision():
    inbox = ROOT / "inbox" / "test-alias-operations-manager.md"
    inbox.write_text(
        "---\n"
        "title: Operations Manager capture\n"
        "entity: Operations Manager\n"
        "type: ROLE\n"
        "provenance:\n"
        "  - https://example.com/alias-gate\n"
        "updated: 2026-08-25\n"
        "---\n\nbody\n",
        encoding="utf-8",
    )
    try:
        r = run("validate.py")
        check("validate: inbox entity matching a library ALIAS is an error",
              r.returncode == 1 and "Operations Manager" in r.stdout
              and "alias" in r.stdout.lower(),
              f"rc={r.returncode} out={r.stdout[-400:]!r}")
    finally:
        inbox.unlink()


# --- invariant: temporal keys are legal vocabulary ------------------------

def test_temporal_keys():
    f = ROOT / "inbox" / "test-temporal.md"
    f.write_text(
        "---\n"
        "title: Temporal test\n"
        "entity: Temporal Test Entity\n"
        "type: PROCESS\n"
        "valid_from: 2026-03-01\n"
        "valid_to: 2026-03-31\n"
        "provenance:\n"
        "  - https://example.com/temporal\n"
        "updated: 2026-08-25\n"
        "---\n\nbody\n",
        encoding="utf-8",
    )
    try:
        r = run("validate.py", "--format", str(f))
        check("validate: valid_from/valid_to are known header keys",
              "unknown header key" not in r.stdout,
              f"out={r.stdout[:300]!r}")
        f.write_text(f.read_text(encoding="utf-8")
                     .replace("valid_to: 2026-03-31", "valid_to: not-a-date"),
                     encoding="utf-8")
        r = run("validate.py", "--format", str(f))
        check("validate: malformed valid_to is an error",
              r.returncode == 1 and "valid_to" in r.stdout,
              f"rc={r.returncode} out={r.stdout[:300]!r}")
    finally:
        f.unlink()


# --- invariant: the library itself stays clean ----------------------------

def test_validate_clean():
    r = run("validate.py")
    check("validate: full library passes with zero errors",
          r.returncode == 0,
          f"rc={r.returncode} out={r.stdout[-600:]!r}")


def main():
    test_edges_tsv()
    test_gold_tables()
    test_recall_stub_description()
    test_recall_hook_mode()
    test_inbox_entity_alias_collision()
    test_temporal_keys()
    test_validate_clean()
    failed = [n for n, ok, _ in RESULTS if not ok]
    print(f"\n{len(RESULTS) - len(failed)}/{len(RESULTS)} passed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
